Entry.create!(uri: "http://www.google.com")
Entry.create!(uri: "http://www.favmonster.com")
Entry.create!(uri: "http://www.stackoverflow.com")
Entry.create!(uri: "http://www.railscast.com")
Entry.create!(uri: "http://www.facebook.com")
